# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'version'
        description: 'Version'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v4
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Build
      run: dotnet build --configuration Release /p:Version=${inputs.version}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${inputs.version} --no-build
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${inputs.version} --no-build --output .
    - name: Push
      run: dotnet nuget push NuGet.Workflow.${inputs.version}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_TOKEN }}
